# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fd00ed3eb1725ad8f0beae81c5c5c092df7a6c51d024ca775282b4cfe5c97da7f96da7683404ce4c1f7e51e194752d13667be231f9fba7ca868d8cae73d4971

test:
  secret_key_base: 5bd2d1624029b7962c0cbec59f1f03e63c8e56cbb642fcf1718c90105504956ef4d715d9ae05e46c1bf0a535e556f1e8839632897e950c2b877bc7ed6e7382f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
